name: Go Lint

on:
  pull_request:
    paths:
      - '**.go'
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Run golangci-lint (Fail on lint errors)
        run: golangci-lint run ./...
